version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: qualyseg-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
